import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './Provider'
import RefreshTokenHandler from './RefreshTokenHandler'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <Navbar />
          <main className="app-background min-h-screen">{children}</main>
        </body>
      </Provider>
    </html>
  )
}
